apiVersion: v1
kind: Secret
metadata:
  name: dotenv
  namespace: bot-vitola
type: Opaque
data:
  DISCORD_TOKEN: TVRJME1qWXdOVE16TnprNU1UazNNRGt4TncuR1JHUnQzLmx4eGZoUy05UkZOVUFhQ0hDWXc3bmwwc3A2SFNER3BSOGFWb3c4Cg==
  CHANNEL_TOKEN: MTI1MTU3ODY2MTM3NTg0MDQ3OQo=
  GEMINI_API_KEY: QUl6YVN5QmdGcS01TUdzaEpsMV9udENuRGNpNEtZR2ZIb0NkYlJNCg==
  CODIGO_DISCORD_CHANNEL_ID_TOKEN: MTI1MTU3ODY2MTM3NTg0MDQ3OQo=
